### ISSUE TITLE
manage.py: error: no such option: --commit

### ISSUE THREAD

**Issue by ollywhitespace** [mysociety/mapit#160]
I'm attempting to import the UK OS data. I'm following the instructions here:
http://mapit.poplus.org/docs/self-hosted/import/uk/ by running:

```
./manage.py mapit_UK_find_parents --commit
```

Which is then displaying:

```
./manage.py: error: no such option: --commit
```

Do the docs just need updating here?

**Comment by dracos** [comment]
As with my other update, the other way round I'm afraid – the documentation is up to date, you are running an older version of the code, updating that should be all you need to do. If you log into your EC2 instance run the install script, as documented at http://mapit.poplus.org/docs/self-hosted/install/install-script/ then it should hopefully update to the latest code (be aware if you've made any local code changes, but it should keep the database fine for example). Or you can hopefully update the repository directly with git and run the `conf/post_deploy_actions.bash` script.

**Comment by ollywhitespace** [comment]
Thanks!
