### ISSUE TITLE
ami installation - admin /media/ not accessible

### ISSUE THREAD

**Issue by ollywhitespace** [mysociety/mapit#162]
I'm following the ami setup instructions here:
http://mapit.poplus.org/docs/self-hosted/install/ami/

I've got everything up and running and I can login to the admin interface. But, when accessing the admin interface the CSS and JS don't appear to be loading correctly - they're all returning 404s.

Do I need to make a tweak to the nginx or some sort of django config file to get this working? Thanks in advance.

**Comment by dracos** [comment]
Hmm, that's odd, I assume it used to work :-/

Okay, I have just done the following to check and it appears to work for your issues:
1. Follow http://mapit.poplus.org/docs/self-hosted/install/ami/ to start AMI, update `general.yml` with country GB and SRID 27700, migrate back and forwards, set up admin user.
2. Follow http://mapit.poplus.org/docs/self-hosted/install/install-script/ to download install script, running `sudo sh install-site.sh --default mapit mapit`
3. That should then include the fix I've just committed for this issue (admin CSS/JS), and update the code for your three other issues. Sorry for the confusion, let us know if that doesn't work for you in some way.

**Comment by ollywhitespace** [comment]
Gotcha. Is fixed after I ran install-site.sh
