### ISSUE TITLE
MapIt Access for a Vote-match type tool

### ISSUE THREAD

**Issue by paullenz** [mysociety/mapit#169]
BiteTheBallot (BTB hereafter) are creating a VAA that is launching on 20th March.

They would like to use post-code --> constituency lookup via the MapIT API

They anticipate up to 0.5 - 1.0m calls a day, spiking at 50 requests per second, 150k in any one hour

Should we set up a new MapIt instance to accommodate this or can the existing instance support this kind of load?

**Comment by stevenday** [comment]
Looking at the stats, I think that would be roughly equivalent to what all the rest of mapit's users did during it's busiest point in the last 7 days, both in in terms of peak and hourly load. 

It seems quite a lot to add on top, so I'd probably be thinking we should give them their own instance. Although, I don't know if we have any real idea of how much load mapit can take, so I'm semi-expecting @dracos to tell me I'm wrong :)

**Comment by paullenz** [comment]
Closing as will be covered by https://github.com/mysociety/Non-Site-Specific/issues/530
