### ISSUE TITLE
Think about ways to authenticate API users with a key

### ISSUE THREAD

**Issue by stevenday** [mysociety/mapit#172]
We have to place limits on commercial use of our MapIt api. The obvious way to do this is to make people use an api key, so that we can track usage against each key.

@dracos pointed out that a problem with naively adding a key authentication step to every request is that it'll mean that requests can no longer be cached by Varnish.

@Flupsy suggests putting the key into the url, and bypassing the key mechanism for internal users (who are most of the traffic anyway). This'll mean that we can at least cache all our internal requests, and external requests on a per user basis.

@mhl, @flupsy, @dracos - what are your thoughts on this?

For context, over the last 24 hours MapIt GB had:
- 192,000 requests
- Somewhere between 120-140,000 of those requests were internal (I'm not sure of all of our IP addresses, but being conservative it's the lower number)
- 126,000 were served from Varnish's cache

Personally, my preference is build the api key system into Django, using a url parameter to pass it in. Then we can manage signups/user accounts etc all from within the site. Other options would be to try to get Varnish to do it, or build/use some other kind of intermediary proxy that just does api key authentication.

**Comment by dracos** [comment]
If we assume that many things are cached by varnish without a key, this means performance on any new (to that commercial user) URL will be worse on any of those lookups than if they hadn't supplied a key, which doesn't feel right. I do also very much like the fact that MapIt is basically read-only; it makes things much easier from its point of view, and I think adding any sort of authentication could complicate it quite a bit. I think my suggestion would be to do it in varnish, I see https://code.google.com/p/varnish-apikey/ does something similar using redis to store the API related configuration/logs. This would also let you log things that are being returned by varnish, which otherwise are not counted.

**Comment by dracos** [comment]
If you don't care about varnish responses, then some optional middleware/a separate app that didn't interfere with the rest of the code would probably be fine, yeah, though you do have to worry about logging/looking up the key on every request.

**Comment by stevenday** [comment]
As an expansion on "some other kind of intermediary proxy" @dracos pointed me to: www.mashape.com which is a commercial instance of exactly this.

**Comment by stevenday** [comment]
So I've played with varnish-apikey a little, and it seems to work after a little bit of fiddling with the makefile to get it installed in the right place on Ubuntu 12.04. It looks like we could simplify it a fair bit, but it does enough of what we want from a Varnish side to make api keys work.

I'm a bit worried about the code though, it was created/last updated in 2012, and the Varnish module it relies on to talk to Redis is unsupported. There are a couple of alternative modules that look slightly better, but none of it is hugely confidence inspiring. There are also quite a few "TODO"s in the module code, but it's not an awful lot of code in all, so it's mainly the dependencies that are a worry.

If we went this way, we'd also have to consider how we administer the api keys. `varnish-apikey` comes with a command line tool to add/remove users and their keys, but that would be a very manual process. Really we'd want to make it happen automatically through people being able to sign up on Mapit. This would mean creating a Django app to talk to the Redis server that holds the keys. There's an example set of PHP scripts that we could copy from to do that, but I guess we should at least wireframe the user experience first. The same is true of any approach though.

**Comment by stevenday** [comment]
FYI: I've forked the varnish-apikey project here: https://github.com/mysociety/varnish-apikey and stripped it back to the most basic version I can. It seems a lot more manageable now! 

I think before I go any further though we should have a chat about this in person, so I've added an item to the all team meeting agenda for next week.

**Comment by stevenday** [comment]
I'm going to close this ticket in favour of #173 and #174
