### ISSUE TITLE
All related area links for Na h-Eileanan an Iar throw 500 errors

### ISSUE THREAD

**Issue by andylolz** [mysociety/mapit#180]
The following links all throw errors:

 * http://mapit.mysociety.org/area/14444/touches.html
 * http://mapit.mysociety.org/area/14444/overlaps.html
 * http://mapit.mysociety.org/area/14444/covered.html
 * http://mapit.mysociety.org/area/14444/covers.html
 * http://mapit.mysociety.org/area/14444/coverlaps.html
 * http://mapit.mysociety.org/area/14444/intersects.html

**Comment by dracos** [comment]
Yes, and others will do as well (no way of telling which without trying them all, really). This is a wontfix, I'm afraid, the areas are far too complex for those queries to run in any sort of sensible time. If you need this information, you will have to set up your own instance.

**Comment by andylolz** [comment]
That’s fine – not a problem. I just ran into the error and thought I should report it.
