### ISSUE TITLE
Links to toolserver.org are 404ing

### ISSUE THREAD

**Issue by chrismytton** [mysociety/mapit#195]
The "WGS84 lat/lon" links on [html results pages](http://mapit.mysociety.org/postcode/SW1A1AA.html) link to [http://toolserver.org/~geohack/](http://toolserver.org/~geohack/geohack.php?params=51.5010089365;-0.141587600123), which is returning a 404.

It seems that the geohack tool has been moved to https://tools.wmflabs.org/geohack, so the link should be to something like https://tools.wmflabs.org/geohack/geohack.php?params=51.5010089365;-0.141587600123.

**Comment by dracos** [comment]
Sigh at them not leaving a redirect, thanks for spotting.
