### ISSUE TITLE
MapIt API returning 404 for some partial postcodes of London (i.e. EC1)

### ISSUE THREAD

**Issue by ciacicode** [mysociety/mapit#198]
While using the API with a standard list of partial postcodes for London I noticed the following postcodes return a not found at http://mapit.mysociety.org/postcode/partial/

EC1
EC2
EC3
EC4
SW1
W1
W1M
WC1
WC2

Why are those postcode areas not working with mapit?

**Comment by dracos** [comment]
MapIt uses postcode districts as its partial postcodes, and as e.g. https://en.wikipedia.org/wiki/EC_postcode_area says, the postcode districts of EC1 include the letter after; http://mapit.mysociety.org/postcode/partial/EC1A.html works okay.

Also, W1M and others in that area were recoded in 2000 – http://www.royalmail.com/sites/default/files/postcode-updates-historical-info.pdf – so I think you need a more up-to-date list :) Hope that's helpful.

**Comment by ciacicode** [comment]
Thank you!
