### ISSUE TITLE
'invalid OFT field name given: "CODE"' when importing uk data

### ISSUE THREAD

**Issue by OmegaDroid** [mysociety/mapit#213]
I have been following the instructions at http://mapit.poplus.org/docs/self-hosted/import/uk/ and am running into the following error at the `mapit_UK_import_boundary_line` stage.

```
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File ".../site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File ".../site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".../site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File ".../site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File ".../site-packages/django/core/management/base.py", line 623, in handle
    label_output = self.handle_label(label, **options)
  File ".../site-packages/mapit_gb/management/commands/mapit_UK_import_boundary_line.py", line 59, in handle_label
    ons_code = feat['CODE'].value if feat['CODE'].value not in ('999999', '999999999') else None
  File ".../site-packages/django/contrib/gis/gdal/feature.py", line 43, in __getitem__
    i = self.index(index)
  File ".../site-packages/django/contrib/gis/gdal/feature.py", line 120, in index
    raise OGRIndexError('invalid OFT field name given: "%s"' % field_name)
django.contrib.gis.gdal.error.OGRIndexError: 'invalid OFT field name given: "CODE"'
```

I'm running:
Django==1.8.6
django-mapit==1.4
Python 3.4.3+

Any help on this would be much appreciated :)

**Comment by dracos** [comment]
Which data files precisely are you trying to import? (What is the command line you are running?) The latest Boundary-Line includes supplementary data which is not in the same format as the normal data. All the normal files do have a CODE attribute.

**Comment by OmegaDroid** [comment]
the command I'm running is:

```
./manage.py mapit_UK_import_boundary_line \
    --control=mapit_gb.controls.first-gss --commit \
    `\ls /tmp/uk-os/Data/Wales/*.shp|\grep -v high_water`
```

I am downloading the data from http://parlvid.mysociety.org/os/ and extracting the zips to `/tmp/uk-os/`

Running on the GB directory seems to work until I get this error:
```
ONS code E04012604 is used for Carlton CP and Badgers Mount CP
```

Could this be an order dependence issue? Originally I was collecting all the .shp files into a single directory and running on all of them at the same time and hitting the error straight away.

**Comment by dracos** [comment]
The `Wales` directory is not standard Boundary-Line, but an extra output of community wards. You will need to use the generic import script, or adapt your own, to import that data. The `GB` directory in the October 2015 Boundary-Line is the directory for which the Boundary-Line import script is written.

The ONS error you get is because this Boundary-Line must have a mistake in it, giving two parishes the same ONS code (they should be unique). E04012604 is Carlton CP, Badgers Mount CP should be E0401260**5**. You will have to write your own control function to skip/fix this issue, or wait for us to do it when we deal with importing it on our own servers, #210.

**Comment by dracos** [comment]
The control file that works around the problems with the current Bounary-Line as outlined above can be seen at 110298d2074c9626f6abbc626cbacf8fe0f2f99b (hopefully merged soon).
