### ISSUE TITLE
Unknown command: 'syncdb' django 1.9

### ISSUE THREAD

**Issue by angelicanino** [mysociety/mapit#221]
Trying to install a local mapit, it stops with this line:

Unknown command: 'syncdb'
Type 'manage.py help' for usage.

django does not support syncdb command, now uses migrate instead.

**Comment by dracos** [comment]
Thanks, I've removed the syncdb line from the docs, it's no longer necessary.

**Comment by angelicanino** [comment]
Hi, there is something need to be done to try to install again?
I get the next lines:

Adding unix user... already done
Updating APT sources... done
Cloning or updating repository... updating... There were changes in the working tree in /var/www/mapit/mapit; exiting.

Thanks

**Comment by dracos** [comment]
You can't run the install script if you have made changes to the git checkout, I'm afraid. I believe I have committed a fix to the repo, so running the install script on a clean git checkout should be okay.
