### ISSUE TITLE
problem with import kml

### ISSUE THREAD

**Issue by daeynasvistas** [mysociety/mapit#224]
File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/gdal/datasource.py", line 75, in __init__
    raise GDALException('Could not open the datasource at "%s"' % ds_input)
django.contrib.gis.gdal.error.GDALException: Could not open the datasource at "/tmp/gadm_data/PRT_adm0.kml"

impossible to import kml, following import instruction http://mapit.poplus.org/docs/self-hosted/import/gadm/

**Comment by dracos** [comment]
I'm assuming you worked this out, but for anyone else coming across this, that error means that that file does not exist at that location.
