### ISSUE TITLE
Error 500 on http://global.mapit.mysociety.org/area/792636/covers.html

### ISSUE THREAD

**Issue by jbci** [mysociety/mapit#233]
the timeout is too small.
i tried installing the tool locally to see the logs, everything looked ok
so i increased the timeout and now it's fine. maybe you can consider doing it too.
anyway thanks for such a great tool.

**Comment by dracos** [comment]
I'm afraid we won't currently be increasing the timeout, we have to be mindful of not overloading our server with too many large requests. Glad you managed to install it locally instead and glad you like it.
