### ISSUE TITLE
Allow users to request charitable/not-for-profit status with their signup

### ISSUE THREAD

**Issue by BenJam** [mysociety/mapit#250]
In order to improve the process for identifying charitable users it would be good to extend #174 to include a checkbox akin to 'Request charitable/not-for-profit account' which includes a text field with some guidance like 'Please include details of your organisation and/or project. Include your registered charity or company number if applying on behalf of an organisation.'

A request should fire an enquiry email for review and a notice that we will review this, in the meantime thy can use the free quota.

**Comment by dracos** [comment]
UK specific, moved to https://github.com/mysociety/mapit.mysociety.org/issues/24
