### ISSUE TITLE
Unable to Load kml file generated from shp file 

### ISSUE THREAD

**Issue by MTRNord** [mysociety/mapit#256]
Hopefully my last issue:
After I convert the  shapefile from gadm I want to import the data. Result is: https://hub.docker.com/r/nordgedanken/mapit-germany-docker/builds/br4esjabnbxbkmkd9moc99u/
Full code is here: https://github.com/Nordgedanken/mapit-germany-docker/tree/93439bde2fdd5a7570dcd6807debab88aea506b4
The import goes trough the import.sh where it crashes.

**Comment by dracos** [comment]
The import script should import Shapefiles fine directly, no need to convert to KML. I'm not sure what the issue is, it says it can't find the file, which perhaps means it is the strange #231 that we've never been able to track down the cause :-/ But the issue doesn't appear to lie with MapIt itself, I have tested the files, and they work for me, Shapefile or KML:

```bash
$ curl -O http://biogeo.ucdavis.edu/data/gadm2.8/shp/DEU_adm_shp.zip
$ unzip -d DEU DEU_adm_shp.zip 
$ ogr2ogr -f "KML" -dsco NameField=NAME_ENGLI DEU/DEU_adm0.kml DEU/DEU_adm0.shp
$ python manage.py mapit_import --generation_id 1 --area_type_code CTR --name_type_code gadm --country_code DEU DEU/DEU_adm0.kml
Importing from DEU/DEU_adm0.kml
(will not save to db as --commit not specified)
  looking at 'Germany'
$ python manage.py mapit_import --generation_id 1 --area_type_code CTR --name_type_code gadm --country_code DEU DEU/DEU_adm0.kml --commit
Importing from DEU/DEU_adm0.kml
  looking at 'Germany'
.
$ python manage.py mapit_import --generation_id 1 --area_type_code CTR --name_type_code gadm --country_code DEU --name_field NAME_ENGLI DEU/DEU_adm0.shp
Importing from DEU/DEU_adm0.shp
(will not save to db as --commit not specified)
  looking at 'Germany'
$ python manage.py mapit_import --generation_id 1 --area_type_code CTR --name_type_code gadm --country_code DEU --name_field NAME_ENGLI DEU/DEU_adm0.shp --commit
Importing from DEU/DEU_adm0.shp
  looking at 'Germany'
.
$
```

So sorry I can't be of more assistance.

**Comment by MTRNord** [comment]
I really think I run into #231 because both tries (kml and shapefile) are failing in the same way. I will try to downgrade my python. Maybe that will help

**Comment by MTRNord** [comment]
Same error with trusty and postgresql 9.3 (instead 9.4)

**Comment by MTRNord** [comment]
ok installing django 1.8 works. with the 1.10 version it always fails

**Comment by dracos** [comment]
Okay, thanks for letting us know, will continue trying to find out what it is on #231.
