### ISSUE TITLE
Problem with loading Postal Codes.

### ISSUE THREAD

**Issue by MTRNord** [mysociety/mapit#257]
At the very and of this Log I got an error that the Langitude could not be converted from String to Float. Is there a way to work around this error? (I already saw that there are some Numbers that seem to miss the point in it. 

Log: https://hub.docker.com/r/nordgedanken/mapit-germany-docker/builds/bwqb5z3ylbgn6mwdqddcz6o/
CSV File: https://www.aggdata.com/download_sample.php?file=de_postal_codes.csv
Docker Github: https://github.com/Nordgedanken/mapit-germany-docker/tree/5938839db231d26bc5b7e55acb30f47aae03c788

**Comment by dracos** [comment]
The error message says the string "Latitude" can't be converted to a number. That's because the CSV file has a header row which the code is trying to process. The import command has a parameter specifically to ignore a header row.

**Comment by MTRNord** [comment]
ah I didn't see that one because it wasn't In the text in the Documentation only in the Example

**Comment by dracos** [comment]
Yes, it's not particularly clear that it's giving you the "Other options", ie. on top of the ones in the example above. It might as well duplicate them!
