### ISSUE TITLE
How to add Description of code_type without able to write into terminal (docker)

### ISSUE THREAD

**Issue by MTRNord** [mysociety/mapit#258]
I have as command `su -l -c ". /var/www/mapit/virtualenv-mapit/bin/activate; /var/www/mapit/mapit/manage.py mapit_import --generation_id 1 --area_type_code $CODE --name_type_code binfo --country_code DE --name_field $NAME_FIELD --code_field $CODE_FIELD --code_type osm_rel /data/$NAME.shp --commit" mapit` and it says `Please give a description for code type osm_rel:`.
I tried to do it with `echo "INSERT INTO mapit_type (code, description) VALUES ('osm_rel', 'OSM relation ID'); INSERT INTO mapit_nametype (code, description) VALUES ('osm_rel', 'OSM relation ID');" | su -l -c ". /var/www/mapit/virtualenv-mapit/bin/activate; psql mapit" mapit` because that one worked for all other descriptions but not for this one :/

**Comment by dracos** [comment]
`mapit_type` is the area type (country, council, etc). You want to insert into the `mapit_code_type` table to insert a code type.
In general, you are probably better off creating a fixture file and importing that, like the ones that already exist. See e.g. mapit_gb/fixtures/uk.json which is loaded in with "python manage.py loaddata uk". No need to have manual SQL commands.

**Comment by MTRNord** [comment]
Ok tanks :) I will make an json file than
