### ISSUE TITLE
Postcodes not working correct

### ISSUE THREAD

**Issue by MTRNord** [mysociety/mapit#259]
In Germany we have postcodes like 24963 and not like the GB ones.
When I search the nearest to an lat long it gives the correct postcode but when I search the Postcode it fails with `{"code": 400, "error": "Postcode '24963' is not valid."}`. Url I used in my Mapit is: `http://192.168.178.66:8020/postcode/24963`.

The CSV with the Data in it is: `(Link removed)` (link will be removed when issue closed because I don't own the data in it).
How I import it `./manage.py mapit_import_postal_codes --code-field 1 --coord-field-lon 6 --coord-field-lat 7 --header-row /data/de_postal_codes.csv`

**Comment by dracos** [comment]
For one thing, I think you have lon and lat the wrong way round :)

For the main thing, mapit does not know how to validate a postcode by default, so assumes they're all invalid (perhaps this should be the opposite, but it does make you add the necessary code!). You need to create a countries file, e.g `mapit_de/countries.py` (see the existing entries in e.g. `mapit_no`), add it to `mapit/countries/__init__.py`, and set your `COUNTRY` configuration variable appropriately. Then it will use your validation function to check whether the provided postcode is valid.

**Comment by MTRNord** [comment]
I more think the CSV is wrong :) because when I use the fields like in the CSV And use the right coord in mapit by nearest I am at the other end of Germany so this is an workaround for it :) And ok I will work on that

**Comment by dracos** [comment]
Mapit nearest URL is lon,lat please note.

**Comment by MTRNord** [comment]
Ah ok than did that irritated me :)
