### ISSUE TITLE
Unable to import Shapefiles or Geojson

### ISSUE THREAD

**Issue by MTRNord** [mysociety/mapit#261]
First: I am aware of #231 but not shure if it is the error, because the PR mentioned there is also in my local Version of Mapit.

I get my Shapefile and GeoJson from https://osm.wno-edv-service.de/boundaries/ (Country I completly exported is Germany) but when I wan't to import it in Mapit I get: `django.contrib.gis.gdal.error.GDALException: Could not open the datasource at "data/Germany.shp"`

Full Log: https://hub.docker.com/r/nordgedanken/mapit-germany-docker/builds/baycazxxvvrd5mkplnzsb5a/ (Shows only the Shapefile Error but same error comes with Geojson Version)
Github Project: https://github.com/Nordgedanken/mapit-germany-docker/tree/105802a6e4cea0d614b4a8972c21b6f5c9bc42b6

**Comment by dracos** [comment]
You are echoing "File Shapefile exists" but you are not actually testing that it does at the location you are importing. It does not. As you `su -l` to the mapit user, your current working directory will switch for that line to that user's home directory, and therefore `data/Germany.shp` will not exist, given its location is actually `/data/Germany.shp` (same as with the imports that work fine).

,Please could you stop opening issues that are issues with your Dockerfile, and not with MapIt. You have your own repository, please open issues there and try and only open issues on MapIt that you believe are actual issues with MapIt, after you have debugged the issue yourself as much as possible.

Aside, why have you copied all of mapit_gb/countries? None of that makes any sense in your use.
