### ISSUE TITLE
Where to get the "City of London Corporation"?

### ISSUE THREAD

**Issue by torotil** [mysociety/mapit#267]
On http://mapit.mysociety.org/postcode/EC2Y8DS.html the postcode is part of LBO-area "City of London Corporation" - but when I import the UK data following http://mapit.poplus.org/docs/self-hosted/import/uk/ there is no such area. Also grepping for this string in the data-files did not reveal anything. So … How can I get this dataset?

**Comment by dracos** [comment]
It is in Boundary-Line, in district_borough_unitary_region.shp, but with a different name:
  NAME (String) = City and County of the City of London
  AREA_CODE (String) = LBO
  DESCRIPTIO (String) = London Borough
  FILE_NAME (String) = GREATER_LONDON_AUTHORITY
  NUMBER (Real) =         552
  NUMBER0 (Real) =        1469
  POLYGON_ID (Real) =       51187
  UNIT_ID (Real) =       11105
  CODE (String) = E09000001
  HECTARES (Real) =      314.942
  AREA (Real) =       24.546

Are you saying it doesn't appear in your installation under that postcode, or that it just has a different name?

**Comment by torotil** [comment]
Ah. No I think everything is perfect then. The name is just so different that I was not sure whether it even meant the same area. So I guess this is a non-issue then. Thanks for clearing it up!
