### ISSUE TITLE
October Boundary-Line release

### ISSUE THREAD

**Issue by dracos** [mysociety/mapit#268]
- [x] Put in our [cache](http://parlvid.mysociety.org/os/)
- [x] Import into mapit.mysociety.org

**Comment by verblet** [comment]
Does this release cover the Scottish Local Authority ward boundary changes? (see: http://www.lgbc-scotland.gov.uk/reviews/5th_electoral/)

**Comment by dracos** [comment]
No, the Ordnance Survey Boundary Line main product only includes 'live' boundaries, which in that case will be the May 2017 elections. They have published forward dated English ward boundaries in advance for a couple of years, but that's all.
 
The May release contains the majority of changes each year, the October release only a few. This October, it renames three parishes, implements one Parish Order, amends some water marks, and other tidyings.

Given e.g. http://www.lgbc-scotland.gov.uk/maps/datafiles/index_1995_on.asp if you contacted the LGBC Scotland, I dare say they may well be open to publishing the boundaries of their recommendations somewhere (their map viewer displays them so I assume the data is available).

**Comment by verblet** [comment]
The recommendations have been finalised (last week I believe) so these will be the ward boundaries for the 2017 local elections. Not sure if that affects things?

**Comment by dracos** [comment]
Yes, that's what I said, the new ward boundaries for Scotland will be in the May 2017 Ordnance Survey Boundary-Line release. They are not in this October 2016 release.

**Comment by verblet** [comment]
Oh okay, thanks!

**Comment by dracos** [comment]
Importing/imported now.

**Comment by davidbasalla** [comment]
Hello, we're just looking into updating our boundary line dataset. We wanted to ask if you were aware of the note on https://www.ordnancesurvey.co.uk/opendatadownload/products.html and if your cached dataset is the newest one?

> Update 19/10/2016 - As part of our ongoing commitment to ensure accuracy in our products, we identified a slight error in the October 2016 release (release date 01/10/2016) of Boundary-Line. If you have already downloaded/ordered this, we would recommend downloading the product again to ensure the information you are using is as accurate and up to date as possible.

Also as an aside, we were curious why there was no control file for this import? Does that mean there were no big changes for this dataset? 

Thank you!

**Comment by dracos** [comment]
Oh, thanks, no, I hadn't seen that. Ours is the old version, I've updated our cache and will go and investigate what the "slight error" was.
There were no changes, indeed, there normally aren't (m)any in the October release.

**Comment by dracos** [comment]
Sigh, their new release hasn't rounded the co-ordinates to 1 decimal place as normal, which makes it very hard to see if there's any *actual* change.

**Comment by dracos** [comment]
Okay, after some processing to make everything 1 decimal place, there is no difference at all in any of the files we care about that I can see. So I'm not sure what to do now, but I don't think there's any urgency.
