### ISSUE TITLE
/area/[area ID]/geometry returns GeoQuerySet object has no attribute 'collect'

### ISSUE THREAD

**Issue by altinukshini** [mysociety/mapit#271]
I did a clean installation of mapit and imported some dummy data from gadm.org.

When I enter the /area/[area ID]/geometry path in browser I get the following:

![image10](https://cloud.githubusercontent.com/assets/1146789/20248844/c0b948aa-a9ec-11e6-9679-4376c4f79525.png)

I'm using Mapit Version 1.5.1

Any idea why could this be happening?

**Comment by davea** [comment]
It looks as though MapIt is [calling a function](https://github.com/mysociety/mapit/blob/19763dd27ffa09e06fc0923cbba2d54f5cc4ab52/mapit/views/areas.py#L286) that was [removed in Django 1.10](https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10).

As a temporary workaround until we fix this, could you perhaps use Django 1.9? `pip install 'django<1.10'` should do the trick.

**Comment by altinukshini** [comment]
@davea thanks a lot for the suggestion. Using 1.9 indeed fixed the bug. However, there still seems to be issues such as the following:

![screenshot-mapit-id](https://cloud.githubusercontent.com/assets/1146789/20303873/d19ef68c-ab2d-11e6-8119-5d1cb2f40ee7.jpg)

The encoding can be ignored, I could just use international names as defaults.
![screenshot-mapit-encoding](https://cloud.githubusercontent.com/assets/1146789/20303874/d1a1977a-ab2d-11e6-864d-779be3918252.jpg)

These also result into FixMyStreet crashing bcs instead of receiving json fixmystreet gets a html (with errors) or similar.

**Comment by dracos** [comment]
The “int object has no attribute ID” implies you do not have an active generation. If you have an active generation, that error should go away. I guess the code is assuming no-one will be making those queries before at least one generation is made active, though it could certainly error better!

The encoding issue - this indeed looks to be a bug, only when looking at the geometry page of the admin (listing the same area on the areas page is fine, for example, we should handle encoded characters correctly) I’ve opened https://github.com/mysociety/mapit/issues/272 for that.

Hope that’s helpful.

**Comment by dracos** [comment]
Sorry, meant to include a couple of links: http://mapit.poplus.org/docs/self-hosted/import/boundaries/ and http://mapit.poplus.org/docs/self-hosted/how-data-is-stored/ talk about generations and activating them after you have imported you data. They are so you can import new data before making it ‘live’.

**Comment by dracos** [comment]
Thanks, the issue of using `collect()` and the geometry admin page bug should both be fixed, have pushed version 1.5.2 to PyPI.

**Comment by altinukshini** [comment]
Awesome! Thanks a lot guys! :)
