### ISSUE TITLE
List of UK towns/cities

### ISSUE THREAD

**Issue by bee-keeper** [mysociety/mapit#281]
Hi there,

Is there some data source/combination of sources that would enable me to query for a list of UK towns and cities ideally linked to an area/local authority/county?  Has anyone done this?  Any ideas?

Thanks in advance,

**Comment by dracos** [comment]
Mapping a placename to a location is the job of a geocoder – you may want to look at things like <a href="https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-names.html">OS Open Names</a> (download or API), OpenStreetMap's <a href="http://nominatim.openstreetmap.org">Nominatim</a>, or big mapping providers such as <a href="https://developers.google.com/maps/documentation/geocoding/start">Google</a> or <a href="https://msdn.microsoft.com/en-us/library/ff701713.aspx">Bing</a>.

Once you have geocoded a place name to a point, you could then use MapIt to find out what area that point was in. If you wanted more precision (e.g. you somehow got the shape of a city in some aspect (travel-to-work area?) and wanted to know what local authorities that area covered), you'd need to import that shape and the local authority shapes into a database and do an overlapping comparison. You could use an installation of MapIt for this part, too, or do it directly.

We have a community mailing list as mentioned on https://www.mysociety.org/subscribe/ that might be a good place to ask this also.

**Comment by bee-keeper** [comment]
Hi thanks for the reply.  One last question, I just downloaded and installed the boundary data but didn't see any area type that resembles a county.  Is there some county boundary data source we can use with mapit to get geometry for county areas?

**Comment by dracos** [comment]
It depends what you mean by "county" :) "CTY" are the county councils. If you mean the things commonly referred to as the ceremonial counties, then our wiki page at https://github.com/mysociety/mapit/wiki/UK-Ceremonial-Counties should be helpful.

**Comment by bee-keeper** [comment]
That's exactly what I was looking for - thanks!
