### ISSUE TITLE
Limit usage reached - documentation not clear

### ISSUE THREAD

**Issue by CHAIN-Admin** [mysociety/mapit#297]
We've agreed a charity plan up to 10,000 calls per month and updated our new API token, but all our requests are returning a 429 status code - usage limit reached error. The documentation doesn't make clear what we need to do to address the problem. Please could you advise or point us to relevant docs.

**Comment by dracos** [comment]
Hi, sorry to hear you're having problems. To help, I'll need to know which address you signed up to MapIt with, and preferably to see the code you're using to make requests to MapIt, as presumably there is an issue with how you are specifying the API key. Probably easiest if you contact us via https://mapit.mysociety.org/contact so we can provide more detailed information and I'm sure we can get it sorted. If you log in to your account at https://mapit.mysociety.org/ then instructions for using the key are given on the `API Keys` page.

**Comment by dracos** [comment]
Ah, I see you did email and I was just checking here first! You should get a reply very shortly.

**Comment by dracos** [comment]
Resolved by email; wrong query parameter key was being used.
