### ISSUE TITLE
/code/gss endpoint sometimes doesn't redirect

### ISSUE THREAD

**Issue by chris48s** [mysociety/mapit#342]
Usually this works. For example https://mapit.mysociety.org/code/gss/E05009488.html redirects to https://mapit.mysociety.org/area/145672.html as expected.

Sometimes it doesn't though. For example https://mapit.mysociety.org/code/gss/E05010063.html raises a 404 but I would expect it to redirect to https://mapit.mysociety.org/area/145312.html the same as https://mapit.mysociety.org/area/E05010063.html does.

**Comment by dracos** [comment]
As with the other calls, it only searches the active generation by default. E05010063 is no longer an active area; the URL works if you add generation=35 or min_generation=35 etc. I realise this seems odd with these identifiers which are meant to be unique, but I could see there being an ID that was repeated in each generation or something, maybe?

**Comment by chris48s** [comment]
Thanks for the quick response :)

> I could see there being an ID that was repeated in each generation or something, maybe?

Right yes - of course. This is definitely the case for OS unit_ids, which can refer to different areas in different generations. For example:

https://mapit.mysociety.org/code/unit_id/44017.html?generation=30
https://mapit.mysociety.org/code/unit_id/44017.html?generation=31

So just to confirm: Is the `/area/<gss>` pattern performing a cross-generation search by design because it only accepts a GSS (which will be unique across generations) and not other identifier types, right?

**Comment by dracos** [comment]
Yes, there is a special UK-only `area_code_lookup` function in mapit_gb/countries.py that checks if the area ID provided, rather than being an integer, matches the old ONS or GSS formats, and if so does a unique lookup on it.

**Comment by chris48s** [comment]
makes sense - cheers :+1:
