### ISSUE TITLE
Support reviewing and uploading new additions to MapIt

### ISSUE THREAD

**Issue by ajparsons** [mysociety/mapit#350]
Need some time from @dracos in March (ideally not too close to the end) to review some pull requests for MapIt that introduce some new statistical geographies. 

https://github.com/mysociety/mapit/pull/349
https://github.com/mysociety/mapit/pull/344
https://github.com/mysociety/mapit/pull/345

And either deploy those changes or help me through the mapit deployment process (whichever makes more sense time-wise).

This can be funded time through the Sheffield deprivation work.

**Comment by dracos** [comment]
All done and live, I think!
