### ISSUE TITLE
CCG boundary update

### ISSUE THREAD

**Issue by CharlieSeagull** [mysociety/mapit#379]
Some CCGs have recently been merged into one:

    • NHS Isle of Wight CCG
    • NHS North Hampshire CCG
    • NHS South Eastern Hampshire CCG
    • NHS Southampton City CCG
    • NHS West Hampshire CCG
    • NHS Fareham and Gosport CCG

are now the `NHS Hampshire, Southampton and Isle of Wight CCG`. Other unfound areas are: 
    • NHS Bedfordshire, Luton and Milton Keynes CCG
    • NHS Black Country and West Birmingham CCG
    • NHS Coventry and Warwickshire CCG
    • NHS Frimley CCG
    • NHS Kirklees CCG
    • NHS North West London CCG
    • NHS Shropshire, Telford and Wrekin CCG

There hasn’t been a mapit update to reflect these changes yet! Is one planned?

**Comment by RichardTaylor** [comment]
Soon to be superseded by #383

**Comment by dracos** [comment]
This has been done with generation 45, e.g. https://mapit.mysociety.org/area/165084.html, sorry for the delay.
