### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by jonkri** [mysociety/mapit#396]
Django 3.2's extended support ends in April 2024.

Should we wait until Django 4.2 LTS is released in April?

For more information about when the Django versions will be supported, see [https://www.djangoproject.com/download/#supported-versions](https://www.djangoproject.com/download/#supported-versions).

**Comment by dracos** [comment]
We generally only fully support the LTS versions, but I think there's a branch where we're already testing version 4, eg https://github.com/mysociety/mapit/actions/runs/2957598693/jobs/4730023713 - but that looks to have been missed off a bit, I'll look to get it merged soon.

**Comment by jonkri** [comment]
Just a friendly reminder. Extended support for Django 3.2 has now ended.

**Comment by dracos** [comment]
Tsch, I thought it was end of April, not start! Anyway, thanks, will look at this now, I don't think there's any issues with 3.2 that would be a concern though at this point.
