### ISSUE TITLE
Unable to clone repo for manually installation of mapit

### ISSUE THREAD

**Issue by frankyfranks** [mysociety/mapit#410]
As per the instructions for a manual installation of mapit at http://code.mapit.mysociety.org/install/ I've attempted the clone the repo;-
$ git clone git://github.com/mysociety/mapit.git
Unfortunately I get an error=Connection timed out. I've tried multiple times but get the same error each time.

Any suggestions or help greatly appreciated or even better if there is a newer install script that works on a current version of Ubuntu or Debian.

Many thanks

**Comment by mikejamesthompson** [comment]
Those instructions are outdated. GitHub dropped support for the Git protocol a while ago:
https://github.blog/2021-09-01-improving-git-protocol-security-github/

You'll need to clone via https or ssh:

```sh
git clone https://github.com/mysociety/mapit.git
```

or

```sh
git clone git@github.com:mysociety/mapit.git
```

**Comment by frankyfranks** [comment]
> Those instructions are outdated. GitHub dropped support for the Git protocol a while ago: https://github.blog/2021-09-01-improving-git-protocol-security-github/
> 
> You'll need to clone via https or ssh:
> 
> ```shell
> git clone https://github.com/mysociety/mapit.git
> ```
> 
> or
> 
> ```shell
> git clone git@github.com:mysociety/mapit.git
> ```

Mike,
Many thanks, that resolved the issue.
