### ISSUE TITLE
Trying to self host MAPIT - any plans to update the install.sh script or AWS AMI?

### ISSUE THREAD

**Issue by frankyfranks** [mysociety/mapit#412]
Thanks for all the work on mapit project but we are struggling to host our own mapit instance.
The installation instructions for mapit are somewhat out of date. 
The AWS AMI for mapit no longer exists.
The mapit install script references out of support versions of Ubuntu and Debian and fails on current versions.
I've tried the manual install method and again failed when using Ubuntu 20.04. 

Are there any plans to update the mapit install script or create an updated AWS AMI?

Regards
Frank

**Comment by mikejamesthompson** [comment]
You could try this and see if it works for you:
https://github.com/mysociety/mapit/pull/413

**Comment by frankyfranks** [comment]
Mike,

That's working for us on an EC2 instance running Ubuntu 20.04.

Thank you so much, now the next challenge for us is importing the relevant post codes required but I'm sure we'll get there.

Many. many thanks
Frank

**Comment by frankyfranks** [comment]
Mike,

Thanks once again for updating the mapit installation script. 

After using the script successfully to install mapit on an EC2 instance I have tried the same on a local machine but unfortunately without success. Details below;-
Host was a clean Ubuntu Server 20.04 LTS with all system updates applied up until 8/12/23 in a Proxmox VM with similar specs to our EC2 mapit server.
I ran your install script the same as before and it appeared to complete without any issue.  Following the recently updated installation instructions I tried to run $ sudo /etc/init.d/mapit restart which failed and I note there is no mapit file in the /etc/init.d/ directory. 
I repeated the install on a clean Ubuntu 20.04 vm (just in case something went amiss) with the same result. 
As this is not really my area of expertise I also tried explicitly installing g++ and python3-venv before running the install script but this made no difference to the outcome.
I have not yet tried doing a clean install on bare metal as I don't have anything immediately available but could probably do so by moving some things around when time allows.

Any advice of now to install on a VM would be greatly appreciated and if I'll be happy to try a few tests if that helps but my expertise is this area is somewhat limited.

Kind regards
Frank

**Comment by dracos** [comment]
#413 has been merged, thanks for the prompt and @mikejamesthompson for providing those updates.
jammy and bookworm support was added in https://github.com/mysociety/commonlib/commit/cde14dea76e8fc81df391f258aac3c71eb6835bb.
I've just run the mapit install script on both focal and jammy servers and it runs without issue, so I'm afraid any problems you are having must be at your own end. If the init.d script has not been created, something must have gone wrong during the running of the install script.
This is a repository for bug reports, not installation support, so I'm going to close this issue now.

**Comment by frankyfranks** [comment]
The purpose of my reply was not for installation support but to report an issue that may be common deployment method, raise a potential issue for the new script, (albeit I missed it was already merged) and offer to undertake some tests under your guidance.
My EC2 instance is running fine thanks to Mike's updated script. I'll try on bare metal and again I'll experiment with a VM and report back my findings/issues in the New Year. 
Wishing all seasons greetings and thanks to all for all your work you do.

Kind regards
Frank
