### ISSUE TITLE
Where can I find the data data to populate my own Mapit server for FixMyStreet ?

### ISSUE THREAD

**Issue by kezzy1966** [mysociety/mapit#416]
Hi, we have installed Mapit on our own server for FixMyStreet. However we cannot find where to get the data from to populate it. I cannot see any mention in posts here or on the My Society/Mapit documentation. Please could someone advise me.

**Comment by dracos** [comment]
This repository is for the source code of the core mapit code. You can import any form of boundary data into MapIt, which can then be used for whatever purpose, including an installation of FixMyStreet. You haven't provided any information as to what data or what installation you are referring to, so I don't know what you're referring to. The documentation at https://code.mapit.mysociety.org/ provides examples of a number of imports, including KML, GADM, UK, and OSM.

**Comment by kezzy1966** [comment]
We are installing a test version of exactly how the national Mapit system works with FixMyStreet. So we require the GPS boundary, council, borough country GPS + Polygon data. There is only general info on the Mapit page you refer about importing postcodes and boundary but nothing on how to replicate the current Mapit Service. Is that data available ?

**Comment by dracos** [comment]
"national Mapit system" - which nation? MapIt is installed in multiple countries around the world. I assume you're talking about the UK, in which case the documentation I've already linked to includes a specific UK page including names of the datasets involved. It's a bit out of date but more than enough for someone to get started.

**Comment by kezzy1966** [comment]
I cannot see any links on that page that help me downloading an existing dataset. 
Is this the page we are talking about:
http://code.mapit.mysociety.org/import/

We are after a data set showing the councils, boroughs etc in the UK.

I only see links to where they try to explain how to create your own data but without examples of council areas in the UK it is fairly useless.  They show how to import postcodes + their specific Long Lats  (which we have done by using data from another source) but the boundary example is for France and again does not have a data set.

**Comment by kezzy1966** [comment]
Do you mean download the GADM data ? 
If so, there are no instructions on how to do it.
