### ISSUE TITLE
Postcode search depends on arbitrary points, when a postcode is better described as an area

### ISSUE THREAD

**Issue by andrewperry** [mysociety/mapit#51]
Currently the Postcode search in mapit is dependent on uploading postcodes as points, when in reality postcodes cover an area.

It would be preferable if postcodes could also be uploaded as areas, in jurisdictions where this data is available, so that more accurate results can be obtained.

**Comment by dracos** [comment]
Feature requests here are existing tickets, e.g. #194 #101 so closing.
